# Generated by Django 4.2.17 on 2025-05-17 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatAccount',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_time',
                 models.DateTimeField(
                     auto_now_add=True,
                     db_index=True)),
                ('modified_time',
                 models.DateTimeField(
                     auto_now=True,
                     db_index=True)),
                ('uuid',
                 models.UUIDField(
                     default=uuid.uuid1,
                     unique=True,
                     verbose_name='UUID')),
                ('openid',
                 models.CharField(
                     max_length=64,
                     unique=True,
                     verbose_name='OpenID')),
                ('unionid',
                 models.CharField(
                     blank=True,
                     max_length=64,
                     null=True,
                     verbose_name='UnionID')),
                ('nickname',
                 models.CharField(
                     blank=True,
                     max_length=64,
                     null=True,
                     verbose_name='昵称')),
                ('avatar_url',
                 models.URLField(
                     blank=True,
                     null=True,
                     verbose_name='头像URL')),
                ('access_token',
                 models.CharField(
                     blank=True,
                     max_length=512,
                     null=True,
                     verbose_name='访问令牌')),
                ('refresh_token',
                 models.CharField(
                     blank=True,
                     max_length=512,
                     null=True,
                     verbose_name='刷新令牌')),
                ('expires_at',
                 models.DateTimeField(
                     blank=True,
                     null=True,
                     verbose_name='令牌过期时间')),
                ('created_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('modified_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('user',
                 models.OneToOneField(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='wechat_account',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信账号',
                'verbose_name_plural': '微信账号',
            },
        ),
    ]
