# Generated by Django 4.2.17 on 2025-01-27 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_time',
                 models.DateTimeField(
                     auto_now_add=True,
                     db_index=True)),
                ('modified_time',
                 models.DateTimeField(
                     auto_now=True,
                     db_index=True)),
                ('uuid',
                 models.UUIDField(
                     default=uuid.uuid1,
                     unique=True)),
                ('name',
                 models.CharField(
                     max_length=255,
                     unique=True)),
                ('intro',
                 models.TextField(
                     blank=True,
                     default='')),
                ('picture',
                 models.ImageField(
                     default=None,
                     null=True,
                     upload_to='')),
                ('title',
                 models.TextField(
                     default=None,
                     null=True)),
                ('birthday',
                 models.DateField(
                     default=None,
                     null=True)),
                ('created_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('modified_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantTitle',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_time',
                 models.DateTimeField(
                     auto_now_add=True,
                     db_index=True)),
                ('modified_time',
                 models.DateTimeField(
                     auto_now=True,
                     db_index=True)),
                ('uuid',
                 models.UUIDField(
                     default=uuid.uuid1,
                     unique=True)),
                ('level',
                 models.PositiveIntegerField(
                     default=None,
                     null=True)),
                ('created_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('modified_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('participant',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='participant_titles',
                     to='club_participants.participant')),
                ('program',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='participant_titles',
                     to='clubs.program')),
            ],
            options={
                'unique_together': {
                    (
                        'program',
                        'participant')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_time',
                 models.DateTimeField(
                     auto_now_add=True,
                     db_index=True)),
                ('modified_time',
                 models.DateTimeField(
                     auto_now=True,
                     db_index=True)),
                ('uuid',
                 models.UUIDField(
                     default=uuid.uuid1,
                     unique=True)),
                ('type',
                 models.CharField(
                     choices=[
                         ('President',
                          'President'),
                         ('VPE',
                          'Vice President Education'),
                         ('VPM',
                          'Vice President Membership'),
                         ('VPPR',
                          'Vice President Public Relationship'),
                         ('Secretary',
                          'Secretary'),
                         ('Treasurer',
                          'Treasurer'),
                         ('SAA',
                          'Sergeant At Arms'),
                         ('IPP',
                          'Immediate Past President'),
                         (None,
                          'None Officer')],
                     default=None,
                     max_length=32,
                     null=True)),
                ('description',
                 models.TextField(
                     blank=True,
                     default='')),
                ('club',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='members',
                     to='clubs.club')),
                ('created_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('modified_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('participant',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='members',
                     to='club_participants.participant')),
            ],
            options={
                'unique_together': {
                    (
                        'club',
                        'type'),
                    ('club',
                     'participant')},
            },
        ),
    ]
