# Generated by Django 4.2.17 on 2025-01-27 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_meetings', '0001_initial'),
        ('club_participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrole',
            name='participant',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='meeting_roles',
                to='club_participants.participant'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='club',
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='meetings',
                to='clubs.club'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_manager',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='meetings',
                to='club_participants.participant'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='modified_by',
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='venue',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='meetings',
                to='club_meetings.meetingvenue'),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={
                (
                    'club',
                    'date')},
        ),
    ]
