# Generated by Django 4.2.17 on 2025-02-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
    ]
