# Generated by Django 4.2.17 on 2025-02-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings',
         '0003_alter_meeting_unique_together_alter_meeting_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingvenue',
            old_name='extra',
            new_name='external',
        ),
    ]
