# Generated by Django 4.2.17 on 2025-02-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0004_rename_extra_meetingvenue_external'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='extra',
            new_name='notes',
        ),
    ]
