# Generated by Django 4.2.17 on 2025-02-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0005_rename_extra_meeting_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingvenue',
            name='external',
            field=models.URLField(default=None, max_length=4096, null=True),
        ),
    ]
