# Generated by Django 4.2.17 on 2025-02-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0006_alter_meetingvenue_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
