# Generated by Django 4.2.17 on 2025-02-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0008_alter_meetingrole_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrole',
            name='type',
            field=models.CharField(
                choices=[
                    ('Host',
                     'Session Host'),
                    ('TME',
                     'Toastmaster Of the Evening'),
                    ('TMD',
                     'Toastmaster Of the Day'),
                    ('TTM',
                     'Table Topics Master'),
                    ('IE',
                     'Individual Evaluator'),
                    ('GE',
                     'General Evaluator'),
                    ('Timer',
                     'Timer'),
                    ('AhCounter',
                     'Ah Counter'),
                    ('Grammarian',
                     'Grammarian'),
                    ('Photographer',
                     'Photographer'),
                    ('ItSupport',
                     'IT Support'),
                    ('SharingMaster',
                     'Sharing Master'),
                    ('ContestChair',
                     'Contest Chair'),
                    ('ElectionChair',
                     'Election Chair'),
                    ('BallotCounter',
                     'Ballot Counter'),
                    ('SAA',
                     'Sergeant At Arms')],
                default='Host',
                max_length=32),
        ),
    ]
