# Generated by Django 4.2.17 on 2025-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0009_alter_meetingrole_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrole',
            name='type',
        ),
        migrations.AddField(
            model_name='meetingrole',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
