# Generated by Django 4.2.17 on 2025-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0010_remove_meetingrole_type_meetingrole_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
