# Generated by Django 4.2.17 on 2025-02-16 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_meetings', '0011_meetingsession_is_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrole',
            name='meeting_session',
        ),
        migrations.CreateModel(
            name='MeetingSessionRoleBinding',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_time',
                 models.DateTimeField(
                     auto_now_add=True,
                     db_index=True)),
                ('uuid',
                 models.UUIDField(
                     default=uuid.uuid1,
                     unique=True)),
                ('created_by',
                 models.ForeignKey(
                     db_constraint=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='+',
                     to=settings.AUTH_USER_MODEL)),
                ('meeting_role',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='meeting_session_role_bindings',
                     to='club_meetings.meetingrole')),
                ('meeting_session',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='meeting_session_role_bindings',
                     to='club_meetings.meetingsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
