# Generated by Django 4.2.17 on 2025-02-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_meetings', '0012_remove_meetingrole_meeting_session_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meetingsessionrolebinding',
            unique_together={('meeting_role', 'meeting_session')},
        ),
    ]
