# Generated by Django 4.2.17 on 2025-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts',
         '0002_remove_transaction_account_balance_account_is_sealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transact_audited',
            field=models.BooleanField(default=False),
        ),
    ]
