# Generated by Django 4.2.17 on 2025-01-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('club_accounts', '0003_transaction_transact_audited'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='club',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transaction_categories',
                to='clubs.club'),
        ),
    ]
